apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeswift-system
resources:
  - serviceaccount.yaml
  - daemonset.yaml
images:
  - name: ghcr.io/projectbeskar/kubeswift/swiftletd
    newTag: latest
