apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeswift-system
resources:
  - serviceaccount.yaml
  - controller-manager-rbac.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/projectbeskar/kubeswift/controller-manager
    newTag: latest
