apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: kubeswift-system
  labels:
    app.kubernetes.io/name: kubeswift
    app.kubernetes.io/component: controller-manager
