apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - classes/default.yaml
  - classes/gpu-pcie.yaml
  - images/ubuntu-noble.yaml
  - images/rocky9.yaml
  - seeds/default.yaml
  - gpu/pcie-single.yaml
