apiVersion: v1
kind: Secret
metadata:
  name: cloud-init-userdata
  namespace: default
type: Opaque
stringData:
  userdata: |
    #cloud-config
    hostname: kubeswift-from-secret
    users:
      - name: kubeswift
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ53Xu8rRSofCQqb91XUgZqQam+5Q2e7tOwr0egG/W5x
---
apiVersion: seed.kubeswift.io/v1alpha1
kind: SwiftSeedProfile
metadata:
  name: with-secret
  namespace: default
spec:
  datasource: NoCloud
  userDataFrom:
    secretKeyRef:
      name: cloud-init-userdata
      key: userdata
  metaData: |
    instance-id: kubeswift-secret-001
    local-hostname: kubeswift-from-secret
