{{- if .Values.gateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: kubeswift-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: kubeswift
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    app.kubernetes.io/name: kubeswift
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
{{- end }}
