//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	swiftv1alpha1 "github.com/kubeswift-io/kubeswift/api/swift/v1alpha1"
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxModel) DeepCopyInto(out *SandboxModel) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxModel.
func (in *SandboxModel) DeepCopy() *SandboxModel {
	if in == nil {
		return nil
	}
	out := new(SandboxModel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxModelStatus) DeepCopyInto(out *SandboxModelStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxModelStatus.
func (in *SandboxModelStatus) DeepCopy() *SandboxModelStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxNetwork) DeepCopyInto(out *SandboxNetwork) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxNetwork.
func (in *SandboxNetwork) DeepCopy() *SandboxNetwork {
	if in == nil {
		return nil
	}
	out := new(SandboxNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxNetworkStatus) DeepCopyInto(out *SandboxNetworkStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxNetworkStatus.
func (in *SandboxNetworkStatus) DeepCopy() *SandboxNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxRootfsStatus) DeepCopyInto(out *SandboxRootfsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxRootfsStatus.
func (in *SandboxRootfsStatus) DeepCopy() *SandboxRootfsStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxRootfsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxRuntimeStatus) DeepCopyInto(out *SandboxRuntimeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxRuntimeStatus.
func (in *SandboxRuntimeStatus) DeepCopy() *SandboxRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxScratchDisk) DeepCopyInto(out *SandboxScratchDisk) {
	*out = *in
	if in.Blank != nil {
		in, out := &in.Blank, &out.Blank
		*out = new(swiftv1alpha1.BlankDiskSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PVCRef != nil {
		in, out := &in.PVCRef, &out.PVCRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxScratchDisk.
func (in *SandboxScratchDisk) DeepCopy() *SandboxScratchDisk {
	if in == nil {
		return nil
	}
	out := new(SandboxScratchDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxScratchDiskStatus) DeepCopyInto(out *SandboxScratchDiskStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxScratchDiskStatus.
func (in *SandboxScratchDiskStatus) DeepCopy() *SandboxScratchDiskStatus {
	if in == nil {
		return nil
	}
	out := new(SandboxScratchDiskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretObjectReference) DeepCopyInto(out *SecretObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretObjectReference.
func (in *SecretObjectReference) DeepCopy() *SecretObjectReference {
	if in == nil {
		return nil
	}
	out := new(SecretObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandbox) DeepCopyInto(out *SwiftSandbox) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandbox.
func (in *SwiftSandbox) DeepCopy() *SwiftSandbox {
	if in == nil {
		return nil
	}
	out := new(SwiftSandbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSandbox) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxList) DeepCopyInto(out *SwiftSandboxList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftSandbox, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxList.
func (in *SwiftSandboxList) DeepCopy() *SwiftSandboxList {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSandboxList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxPool) DeepCopyInto(out *SwiftSandboxPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxPool.
func (in *SwiftSandboxPool) DeepCopy() *SwiftSandboxPool {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSandboxPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxPoolList) DeepCopyInto(out *SwiftSandboxPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftSandboxPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxPoolList.
func (in *SwiftSandboxPoolList) DeepCopy() *SwiftSandboxPoolList {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSandboxPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxPoolSpec) DeepCopyInto(out *SwiftSandboxPoolSpec) {
	*out = *in
	if in.VerifyKeySecretRef != nil {
		in, out := &in.VerifyKeySecretRef, &out.VerifyKeySecretRef
		*out = new(SecretObjectReference)
		**out = **in
	}
	out.Memory = in.Memory.DeepCopy()
	out.Network = in.Network
	if in.KernelProfileRef != nil {
		in, out := &in.KernelProfileRef, &out.KernelProfileRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GPUProfileRef != nil {
		in, out := &in.GPUProfileRef, &out.GPUProfileRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(SandboxModel)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxPoolSpec.
func (in *SwiftSandboxPoolSpec) DeepCopy() *SwiftSandboxPoolSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxPoolStatus) DeepCopyInto(out *SwiftSandboxPoolStatus) {
	*out = *in
	if in.Rootfs != nil {
		in, out := &in.Rootfs, &out.Rootfs
		*out = new(SandboxRootfsStatus)
		**out = **in
	}
	if in.ImageEnv != nil {
		in, out := &in.ImageEnv, &out.ImageEnv
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxPoolStatus.
func (in *SwiftSandboxPoolStatus) DeepCopy() *SwiftSandboxPoolStatus {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxSpec) DeepCopyInto(out *SwiftSandboxSpec) {
	*out = *in
	if in.VerifyKeySecretRef != nil {
		in, out := &in.VerifyKeySecretRef, &out.VerifyKeySecretRef
		*out = new(SecretObjectReference)
		**out = **in
	}
	out.Memory = in.Memory.DeepCopy()
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
	out.Network = in.Network
	if in.KernelProfileRef != nil {
		in, out := &in.KernelProfileRef, &out.KernelProfileRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PoolRef != nil {
		in, out := &in.PoolRef, &out.PoolRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.GPUResourceClaim != nil {
		in, out := &in.GPUResourceClaim, &out.GPUResourceClaim
		*out = new(swiftv1alpha1.GPUResourceClaimSpec)
		**out = **in
	}
	if in.GPUProfileRef != nil {
		in, out := &in.GPUProfileRef, &out.GPUProfileRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.ScratchDisk != nil {
		in, out := &in.ScratchDisk, &out.ScratchDisk
		*out = new(SandboxScratchDisk)
		(*in).DeepCopyInto(*out)
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(SandboxModel)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxSpec.
func (in *SwiftSandboxSpec) DeepCopy() *SwiftSandboxSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSandboxStatus) DeepCopyInto(out *SwiftSandboxStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rootfs != nil {
		in, out := &in.Rootfs, &out.Rootfs
		*out = new(SandboxRootfsStatus)
		**out = **in
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(SandboxRuntimeStatus)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(SandboxNetworkStatus)
		**out = **in
	}
	if in.GPU != nil {
		in, out := &in.GPU, &out.GPU
		*out = new(swiftv1alpha1.GPUStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ScratchDisk != nil {
		in, out := &in.ScratchDisk, &out.ScratchDisk
		*out = new(SandboxScratchDiskStatus)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(SandboxModelStatus)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.TerminalAt != nil {
		in, out := &in.TerminalAt, &out.TerminalAt
		*out = (*in).DeepCopy()
	}
	if in.ExitCode != nil {
		in, out := &in.ExitCode, &out.ExitCode
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSandboxStatus.
func (in *SwiftSandboxStatus) DeepCopy() *SwiftSandboxStatus {
	if in == nil {
		return nil
	}
	out := new(SwiftSandboxStatus)
	in.DeepCopyInto(out)
	return out
}
