//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BARSize) DeepCopyInto(out *BARSize) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BARSize.
func (in *BARSize) DeepCopy() *BARSize {
	if in == nil {
		return nil
	}
	out := new(BARSize)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUTopologyInfo) DeepCopyInto(out *CPUTopologyInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUTopologyInfo.
func (in *CPUTopologyInfo) DeepCopy() *CPUTopologyInfo {
	if in == nil {
		return nil
	}
	out := new(CPUTopologyInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FMPartitionStatus) DeepCopyInto(out *FMPartitionStatus) {
	*out = *in
	if in.GPUIndices != nil {
		in, out := &in.GPUIndices, &out.GPUIndices
		*out = make([]int, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FMPartitionStatus.
func (in *FMPartitionStatus) DeepCopy() *FMPartitionStatus {
	if in == nil {
		return nil
	}
	out := new(FMPartitionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricManagerSpec) DeepCopyInto(out *FabricManagerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricManagerSpec.
func (in *FabricManagerSpec) DeepCopy() *FabricManagerSpec {
	if in == nil {
		return nil
	}
	out := new(FabricManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FabricManagerStatus) DeepCopyInto(out *FabricManagerStatus) {
	*out = *in
	if in.Partitions != nil {
		in, out := &in.Partitions, &out.Partitions
		*out = make([]FMPartitionStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FabricManagerStatus.
func (in *FabricManagerStatus) DeepCopy() *FabricManagerStatus {
	if in == nil {
		return nil
	}
	out := new(FabricManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDevice) DeepCopyInto(out *GPUDevice) {
	*out = *in
	if in.BARSizes != nil {
		in, out := &in.BARSizes, &out.BARSizes
		*out = make([]BARSize, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDevice.
func (in *GPUDevice) DeepCopy() *GPUDevice {
	if in == nil {
		return nil
	}
	out := new(GPUDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostTopology) DeepCopyInto(out *HostTopology) {
	*out = *in
	out.CPUTopology = in.CPUTopology
	if in.NUMANodes != nil {
		in, out := &in.NUMANodes, &out.NUMANodes
		*out = make([]NUMANodeInfo, len(*in))
		copy(*out, *in)
	}
	out.Hugepages1Gi = in.Hugepages1Gi
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostTopology.
func (in *HostTopology) DeepCopy() *HostTopology {
	if in == nil {
		return nil
	}
	out := new(HostTopology)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HugepageInfo) DeepCopyInto(out *HugepageInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HugepageInfo.
func (in *HugepageInfo) DeepCopy() *HugepageInfo {
	if in == nil {
		return nil
	}
	out := new(HugepageInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUMANodeInfo) DeepCopyInto(out *NUMANodeInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUMANodeInfo.
func (in *NUMANodeInfo) DeepCopy() *NUMANodeInfo {
	if in == nil {
		return nil
	}
	out := new(NUMANodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NUMATopologySpec) DeepCopyInto(out *NUMATopologySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NUMATopologySpec.
func (in *NUMATopologySpec) DeepCopy() *NUMATopologySpec {
	if in == nil {
		return nil
	}
	out := new(NUMATopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NVSwitchDevice) DeepCopyInto(out *NVSwitchDevice) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NVSwitchDevice.
func (in *NVSwitchDevice) DeepCopy() *NVSwitchDevice {
	if in == nil {
		return nil
	}
	out := new(NVSwitchDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PCIeTopologySpec) DeepCopyInto(out *PCIeTopologySpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PCIeTopologySpec.
func (in *PCIeTopologySpec) DeepCopy() *PCIeTopologySpec {
	if in == nil {
		return nil
	}
	out := new(PCIeTopologySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGPUNode) DeepCopyInto(out *SwiftGPUNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGPUNode.
func (in *SwiftGPUNode) DeepCopy() *SwiftGPUNode {
	if in == nil {
		return nil
	}
	out := new(SwiftGPUNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftGPUNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGPUNodeList) DeepCopyInto(out *SwiftGPUNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftGPUNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGPUNodeList.
func (in *SwiftGPUNodeList) DeepCopy() *SwiftGPUNodeList {
	if in == nil {
		return nil
	}
	out := new(SwiftGPUNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftGPUNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGPUNodeStatus) DeepCopyInto(out *SwiftGPUNodeStatus) {
	*out = *in
	if in.LastDiscovery != nil {
		in, out := &in.LastDiscovery, &out.LastDiscovery
		*out = (*in).DeepCopy()
	}
	in.Host.DeepCopyInto(&out.Host)
	if in.GPUs != nil {
		in, out := &in.GPUs, &out.GPUs
		*out = make([]GPUDevice, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NVSwitches != nil {
		in, out := &in.NVSwitches, &out.NVSwitches
		*out = make([]NVSwitchDevice, len(*in))
		copy(*out, *in)
	}
	if in.FabricManager != nil {
		in, out := &in.FabricManager, &out.FabricManager
		*out = new(FabricManagerStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGPUNodeStatus.
func (in *SwiftGPUNodeStatus) DeepCopy() *SwiftGPUNodeStatus {
	if in == nil {
		return nil
	}
	out := new(SwiftGPUNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGPUProfile) DeepCopyInto(out *SwiftGPUProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGPUProfile.
func (in *SwiftGPUProfile) DeepCopy() *SwiftGPUProfile {
	if in == nil {
		return nil
	}
	out := new(SwiftGPUProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftGPUProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGPUProfileList) DeepCopyInto(out *SwiftGPUProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftGPUProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGPUProfileList.
func (in *SwiftGPUProfileList) DeepCopy() *SwiftGPUProfileList {
	if in == nil {
		return nil
	}
	out := new(SwiftGPUProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftGPUProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGPUProfileSpec) DeepCopyInto(out *SwiftGPUProfileSpec) {
	*out = *in
	if in.PCIeTopology != nil {
		in, out := &in.PCIeTopology, &out.PCIeTopology
		*out = new(PCIeTopologySpec)
		**out = **in
	}
	if in.NUMATopology != nil {
		in, out := &in.NUMATopology, &out.NUMATopology
		*out = new(NUMATopologySpec)
		**out = **in
	}
	if in.FabricManager != nil {
		in, out := &in.FabricManager, &out.FabricManager
		*out = new(FabricManagerSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGPUProfileSpec.
func (in *SwiftGPUProfileSpec) DeepCopy() *SwiftGPUProfileSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftGPUProfileSpec)
	in.DeepCopyInto(out)
	return out
}
