#!/bin/bash
# source.sh — Phase 2 manual demo: gather source SwiftGuest metadata.
#
# Reads the source SwiftGuest's launcher pod, captures the metadata
# `destination.sh` needs (PVC names, image, source node, etc.), and
# writes them to STATE_FILE for downstream scripts. Idempotent —
# re-running with the same SWIFTGUEST simply re-captures.
#
# Required env vars:
#   SWIFTGUEST   — name of the source SwiftGuest
#
# Optional env vars:
#   NAMESPACE    — defaults to "default"
#   STATE_FILE   — defaults to /tmp/kubeswift-migration-phase2-manual/state.env
#
# After this script:
#   * STATE_FILE contains: SOURCE_POD, SOURCE_NODE, ROOT_PVC, INTENT_CM,
#     SEED_CM (if any), DATA_DISK_PVC (if any), GUEST_ID, NAMESPACE,
#     SWIFTGUEST.
#   * The source pod's full YAML is dumped at $WORKDIR/src-pod.yaml so
#     destination.sh can use it as a template.

set -euo pipefail

: "${SWIFTGUEST:?SWIFTGUEST env var required (name of source SwiftGuest)}"
NAMESPACE="${NAMESPACE:-default}"
STATE_FILE="${STATE_FILE:-/tmp/kubeswift-migration-phase2-manual/state.env}"
WORKDIR="$(dirname "$STATE_FILE")"
mkdir -p "$WORKDIR"

echo "==> Reading SwiftGuest $NAMESPACE/$SWIFTGUEST..."
SOURCE_POD="$(kubectl get swiftguest "$SWIFTGUEST" -n "$NAMESPACE" \
    -o jsonpath='{.status.podRef.name}')"
if [[ -z "$SOURCE_POD" ]]; then
    echo "ERROR: SwiftGuest $NAMESPACE/$SWIFTGUEST has no status.podRef" >&2
    exit 1
fi
echo "    source pod: $SOURCE_POD"

echo "==> Reading source pod spec..."
kubectl get pod "$SOURCE_POD" -n "$NAMESPACE" -o yaml > "$WORKDIR/src-pod.yaml"

SOURCE_NODE="$(kubectl get pod "$SOURCE_POD" -n "$NAMESPACE" \
    -o jsonpath='{.spec.nodeName}')"
echo "    source node: $SOURCE_NODE"

# Extract ConfigMap and PVC references from the source pod's volumes.
INTENT_CM="$(kubectl get pod "$SOURCE_POD" -n "$NAMESPACE" \
    -o jsonpath='{.spec.volumes[?(@.name=="runtime-intent")].configMap.name}')"
echo "    intent CM: $INTENT_CM"

ROOT_PVC="$(kubectl get pod "$SOURCE_POD" -n "$NAMESPACE" \
    -o jsonpath='{.spec.volumes[?(@.name=="root-disk")].persistentVolumeClaim.claimName}')"
echo "    root PVC: $ROOT_PVC"

# seed-config-map is optional (kernel boot has none).
SEED_CM="$(kubectl get pod "$SOURCE_POD" -n "$NAMESPACE" \
    -o jsonpath='{.spec.volumes[?(@.name=="seed-config-map")].configMap.name}' \
    || true)"
echo "    seed CM: ${SEED_CM:-<none>}"

DATA_DISK_PVC="$(kubectl get pod "$SOURCE_POD" -n "$NAMESPACE" \
    -o jsonpath='{.spec.volumes[?(@.name=="data-disk")].persistentVolumeClaim.claimName}' \
    || true)"
echo "    data disk PVC: ${DATA_DISK_PVC:-<none>}"

GUEST_ID="$(kubectl get swiftguest "$SWIFTGUEST" -n "$NAMESPACE" \
    -o jsonpath='{.spec.guestClassRef.name}' || true)"
# guest_id in the intent.json is "<namespace>/<guest-name>"
GUEST_ID="${NAMESPACE}/${SWIFTGUEST}"

echo
cat > "$STATE_FILE" <<EOF
# Phase 2 manual demo state — generated by source.sh
NAMESPACE="$NAMESPACE"
SWIFTGUEST="$SWIFTGUEST"
SOURCE_POD="$SOURCE_POD"
SOURCE_NODE="$SOURCE_NODE"
INTENT_CM="$INTENT_CM"
ROOT_PVC="$ROOT_PVC"
SEED_CM="$SEED_CM"
DATA_DISK_PVC="$DATA_DISK_PVC"
GUEST_ID="$GUEST_ID"
WORKDIR="$WORKDIR"
EOF

echo "==> State written to $STATE_FILE"
cat "$STATE_FILE" | sed 's/^/    /'
echo
echo "Next: TARGET_NODE=<other-node> ./destination.sh"
