//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestConsoleStatus) DeepCopyInto(out *GuestConsoleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestConsoleStatus.
func (in *GuestConsoleStatus) DeepCopy() *GuestConsoleStatus {
	if in == nil {
		return nil
	}
	out := new(GuestConsoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestNetworkInterface) DeepCopyInto(out *GuestNetworkInterface) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestNetworkInterface.
func (in *GuestNetworkInterface) DeepCopy() *GuestNetworkInterface {
	if in == nil {
		return nil
	}
	out := new(GuestNetworkInterface)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestNetworkStatus) DeepCopyInto(out *GuestNetworkStatus) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]GuestNetworkInterface, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestNetworkStatus.
func (in *GuestNetworkStatus) DeepCopy() *GuestNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(GuestNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GuestRuntimeStatus) DeepCopyInto(out *GuestRuntimeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GuestRuntimeStatus.
func (in *GuestRuntimeStatus) DeepCopy() *GuestRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(GuestRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RootDiskSpec) DeepCopyInto(out *RootDiskSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RootDiskSpec.
func (in *RootDiskSpec) DeepCopy() *RootDiskSpec {
	if in == nil {
		return nil
	}
	out := new(RootDiskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGuest) DeepCopyInto(out *SwiftGuest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGuest.
func (in *SwiftGuest) DeepCopy() *SwiftGuest {
	if in == nil {
		return nil
	}
	out := new(SwiftGuest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftGuest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGuestClass) DeepCopyInto(out *SwiftGuestClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGuestClass.
func (in *SwiftGuestClass) DeepCopy() *SwiftGuestClass {
	if in == nil {
		return nil
	}
	out := new(SwiftGuestClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftGuestClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGuestClassList) DeepCopyInto(out *SwiftGuestClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftGuestClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGuestClassList.
func (in *SwiftGuestClassList) DeepCopy() *SwiftGuestClassList {
	if in == nil {
		return nil
	}
	out := new(SwiftGuestClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftGuestClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGuestClassSpec) DeepCopyInto(out *SwiftGuestClassSpec) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	in.RootDisk.DeepCopyInto(&out.RootDisk)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGuestClassSpec.
func (in *SwiftGuestClassSpec) DeepCopy() *SwiftGuestClassSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftGuestClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGuestList) DeepCopyInto(out *SwiftGuestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftGuest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGuestList.
func (in *SwiftGuestList) DeepCopy() *SwiftGuestList {
	if in == nil {
		return nil
	}
	out := new(SwiftGuestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftGuestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGuestSpec) DeepCopyInto(out *SwiftGuestSpec) {
	*out = *in
	if in.ImageRef != nil {
		in, out := &in.ImageRef, &out.ImageRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.KernelRef != nil {
		in, out := &in.KernelRef, &out.KernelRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	out.GuestClassRef = in.GuestClassRef
	if in.SeedProfileRef != nil {
		in, out := &in.SeedProfileRef, &out.SeedProfileRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGuestSpec.
func (in *SwiftGuestSpec) DeepCopy() *SwiftGuestSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftGuestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftGuestStatus) DeepCopyInto(out *SwiftGuestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodRef != nil {
		in, out := &in.PodRef, &out.PodRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(GuestNetworkStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Runtime != nil {
		in, out := &in.Runtime, &out.Runtime
		*out = new(GuestRuntimeStatus)
		**out = **in
	}
	if in.Console != nil {
		in, out := &in.Console, &out.Console
		*out = new(GuestConsoleStatus)
		**out = **in
	}
	if in.LastRestartTime != nil {
		in, out := &in.LastRestartTime, &out.LastRestartTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftGuestStatus.
func (in *SwiftGuestStatus) DeepCopy() *SwiftGuestStatus {
	if in == nil {
		return nil
	}
	out := new(SwiftGuestStatus)
	in.DeepCopyInto(out)
	return out
}
