apiVersion: seed.kubeswift.io/v1alpha1
kind: SwiftSeedProfile
metadata:
  name: minimal
  namespace: default
spec:
  datasource: NoCloud
  userData: |
    #cloud-config
    hostname: kubeswift-guest
    package_update: true
    users:
      - name: kubeswift
        passwd: $6$kubeswift$/2TeJTNbX7JcApzW0gTbSFzCAN4eFcOdnQsI0lVANFpXhHmjqLy7npyhHxvT65kpUd0YKVMBAbRt3MUfV6eCJ.
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
    runcmd:
      - systemctl enable --now getty@ttyS0.service
  metaData: |
    instance-id: kubeswift-001
    local-hostname: kubeswift-guest
