//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftMigration) DeepCopyInto(out *SwiftMigration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftMigration.
func (in *SwiftMigration) DeepCopy() *SwiftMigration {
	if in == nil {
		return nil
	}
	out := new(SwiftMigration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftMigration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftMigrationGuestRef) DeepCopyInto(out *SwiftMigrationGuestRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftMigrationGuestRef.
func (in *SwiftMigrationGuestRef) DeepCopy() *SwiftMigrationGuestRef {
	if in == nil {
		return nil
	}
	out := new(SwiftMigrationGuestRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftMigrationList) DeepCopyInto(out *SwiftMigrationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftMigration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftMigrationList.
func (in *SwiftMigrationList) DeepCopy() *SwiftMigrationList {
	if in == nil {
		return nil
	}
	out := new(SwiftMigrationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftMigrationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftMigrationPodRef) DeepCopyInto(out *SwiftMigrationPodRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftMigrationPodRef.
func (in *SwiftMigrationPodRef) DeepCopy() *SwiftMigrationPodRef {
	if in == nil {
		return nil
	}
	out := new(SwiftMigrationPodRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftMigrationSpec) DeepCopyInto(out *SwiftMigrationSpec) {
	*out = *in
	out.GuestRef = in.GuestRef
	in.Target.DeepCopyInto(&out.Target)
	if in.DowntimeTarget != nil {
		in, out := &in.DowntimeTarget, &out.DowntimeTarget
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftMigrationSpec.
func (in *SwiftMigrationSpec) DeepCopy() *SwiftMigrationSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftMigrationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftMigrationStatus) DeepCopyInto(out *SwiftMigrationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SourcePodRef != nil {
		in, out := &in.SourcePodRef, &out.SourcePodRef
		*out = new(SwiftMigrationPodRef)
		**out = **in
	}
	if in.DestinationPodRef != nil {
		in, out := &in.DestinationPodRef, &out.DestinationPodRef
		*out = new(SwiftMigrationPodRef)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.PreparingStartedAt != nil {
		in, out := &in.PreparingStartedAt, &out.PreparingStartedAt
		*out = (*in).DeepCopy()
	}
	if in.ResumingStartedAt != nil {
		in, out := &in.ResumingStartedAt, &out.ResumingStartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.ObservedDowntime != nil {
		in, out := &in.ObservedDowntime, &out.ObservedDowntime
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ObservedPauseWindow != nil {
		in, out := &in.ObservedPauseWindow, &out.ObservedPauseWindow
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftMigrationStatus.
func (in *SwiftMigrationStatus) DeepCopy() *SwiftMigrationStatus {
	if in == nil {
		return nil
	}
	out := new(SwiftMigrationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftMigrationTarget) DeepCopyInto(out *SwiftMigrationTarget) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftMigrationTarget.
func (in *SwiftMigrationTarget) DeepCopy() *SwiftMigrationTarget {
	if in == nil {
		return nil
	}
	out := new(SwiftMigrationTarget)
	in.DeepCopyInto(out)
	return out
}
