apiVersion: v2
name: kubeswift
description: KubeSwift - Cloud Hypervisor-first Kubernetes VM operator
type: application
version: 0.6.1
appVersion: "0.6.1"
keywords:
  - kubeswift
  - cloud-hypervisor
  - vmm
home: https://github.com/kubeswift-io/kubeswift
sources:
  - https://github.com/kubeswift-io/kubeswift
