apiVersion: v2
name: kubeswift
description: KubeSwift - Cloud Hypervisor-native Kubernetes operator
type: application
version: 0.3.0
appVersion: "0.3.0"
keywords:
  - kubeswift
  - cloud-hypervisor
  - vmm
home: https://github.com/projectbeskar/kubeswift
sources:
  - https://github.com/projectbeskar/kubeswift
