//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeKernelStatus) DeepCopyInto(out *NodeKernelStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeKernelStatus.
func (in *NodeKernelStatus) DeepCopy() *NodeKernelStatus {
	if in == nil {
		return nil
	}
	out := new(NodeKernelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIRef) DeepCopyInto(out *OCIRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIRef.
func (in *OCIRef) DeepCopy() *OCIRef {
	if in == nil {
		return nil
	}
	out := new(OCIRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftKernel) DeepCopyInto(out *SwiftKernel) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftKernel.
func (in *SwiftKernel) DeepCopy() *SwiftKernel {
	if in == nil {
		return nil
	}
	out := new(SwiftKernel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftKernel) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftKernelList) DeepCopyInto(out *SwiftKernelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftKernel, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftKernelList.
func (in *SwiftKernelList) DeepCopy() *SwiftKernelList {
	if in == nil {
		return nil
	}
	out := new(SwiftKernelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftKernelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftKernelSpec) DeepCopyInto(out *SwiftKernelSpec) {
	*out = *in
	out.OCIRef = in.OCIRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftKernelSpec.
func (in *SwiftKernelSpec) DeepCopy() *SwiftKernelSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftKernelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftKernelStatus) DeepCopyInto(out *SwiftKernelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeStatuses != nil {
		in, out := &in.NodeStatuses, &out.NodeStatuses
		*out = make([]NodeKernelStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftKernelStatus.
func (in *SwiftKernelStatus) DeepCopy() *SwiftKernelStatus {
	if in == nil {
		return nil
	}
	out := new(SwiftKernelStatus)
	in.DeepCopyInto(out)
	return out
}
