apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bases/swift.kubeswift.io_swiftguests.yaml
  - bases/swift.kubeswift.io_swiftguestclasses.yaml
  - bases/image.kubeswift.io_swiftimages.yaml
  - bases/seed.kubeswift.io_swiftseedprofiles.yaml
  - bases/kernel.kubeswift.io_swiftkernels.yaml
  - bases/gpu.kubeswift.io_swiftgpuprofiles.yaml
  - bases/gpu.kubeswift.io_swiftgpunodes.yaml
