apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: kubeswift
    app.kubernetes.io/component: controller-manager
