//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIVolumeSnapshotBackend) DeepCopyInto(out *CSIVolumeSnapshotBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIVolumeSnapshotBackend.
func (in *CSIVolumeSnapshotBackend) DeepCopy() *CSIVolumeSnapshotBackend {
	if in == nil {
		return nil
	}
	out := new(CSIVolumeSnapshotBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapturedGuestSpec) DeepCopyInto(out *CapturedGuestSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapturedGuestSpec.
func (in *CapturedGuestSpec) DeepCopy() *CapturedGuestSpec {
	if in == nil {
		return nil
	}
	out := new(CapturedGuestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityRegeneration) DeepCopyInto(out *IdentityRegeneration) {
	*out = *in
	if in.Regenerate != nil {
		in, out := &in.Regenerate, &out.Regenerate
		*out = make([]IdentityRegenerationItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityRegeneration.
func (in *IdentityRegeneration) DeepCopy() *IdentityRegeneration {
	if in == nil {
		return nil
	}
	out := new(IdentityRegeneration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalBackend) DeepCopyInto(out *LocalBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalBackend.
func (in *LocalBackend) DeepCopy() *LocalBackend {
	if in == nil {
		return nil
	}
	out := new(LocalBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemorySnapshotRef) DeepCopyInto(out *MemorySnapshotRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemorySnapshotRef.
func (in *MemorySnapshotRef) DeepCopy() *MemorySnapshotRef {
	if in == nil {
		return nil
	}
	out := new(MemorySnapshotRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Backend) DeepCopyInto(out *S3Backend) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(SecretObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Backend.
func (in *S3Backend) DeepCopy() *S3Backend {
	if in == nil {
		return nil
	}
	out := new(S3Backend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3SnapshotStatus) DeepCopyInto(out *S3SnapshotStatus) {
	*out = *in
	if in.UploadedAt != nil {
		in, out := &in.UploadedAt, &out.UploadedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3SnapshotStatus.
func (in *S3SnapshotStatus) DeepCopy() *S3SnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(S3SnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretObjectReference) DeepCopyInto(out *SecretObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretObjectReference.
func (in *SecretObjectReference) DeepCopy() *SecretObjectReference {
	if in == nil {
		return nil
	}
	out := new(SecretObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotDiskRef) DeepCopyInto(out *SnapshotDiskRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotDiskRef.
func (in *SnapshotDiskRef) DeepCopy() *SnapshotDiskRef {
	if in == nil {
		return nil
	}
	out := new(SnapshotDiskRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestore) DeepCopyInto(out *SwiftRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestore.
func (in *SwiftRestore) DeepCopy() *SwiftRestore {
	if in == nil {
		return nil
	}
	out := new(SwiftRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestoreGuestRef) DeepCopyInto(out *SwiftRestoreGuestRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestoreGuestRef.
func (in *SwiftRestoreGuestRef) DeepCopy() *SwiftRestoreGuestRef {
	if in == nil {
		return nil
	}
	out := new(SwiftRestoreGuestRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestoreList) DeepCopyInto(out *SwiftRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestoreList.
func (in *SwiftRestoreList) DeepCopy() *SwiftRestoreList {
	if in == nil {
		return nil
	}
	out := new(SwiftRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestoreSnapshotRef) DeepCopyInto(out *SwiftRestoreSnapshotRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestoreSnapshotRef.
func (in *SwiftRestoreSnapshotRef) DeepCopy() *SwiftRestoreSnapshotRef {
	if in == nil {
		return nil
	}
	out := new(SwiftRestoreSnapshotRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestoreSpec) DeepCopyInto(out *SwiftRestoreSpec) {
	*out = *in
	out.SnapshotRef = in.SnapshotRef
	out.TargetGuest = in.TargetGuest
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(IdentityRegeneration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestoreSpec.
func (in *SwiftRestoreSpec) DeepCopy() *SwiftRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestoreStatus) DeepCopyInto(out *SwiftRestoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GuestRef != nil {
		in, out := &in.GuestRef, &out.GuestRef
		*out = new(SwiftRestoreGuestRef)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestoreStatus.
func (in *SwiftRestoreStatus) DeepCopy() *SwiftRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(SwiftRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestoreTarget) DeepCopyInto(out *SwiftRestoreTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestoreTarget.
func (in *SwiftRestoreTarget) DeepCopy() *SwiftRestoreTarget {
	if in == nil {
		return nil
	}
	out := new(SwiftRestoreTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshot) DeepCopyInto(out *SwiftSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshot.
func (in *SwiftSnapshot) DeepCopy() *SwiftSnapshot {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotBackend) DeepCopyInto(out *SwiftSnapshotBackend) {
	*out = *in
	if in.CSIVolumeSnapshot != nil {
		in, out := &in.CSIVolumeSnapshot, &out.CSIVolumeSnapshot
		*out = new(CSIVolumeSnapshotBackend)
		**out = **in
	}
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(LocalBackend)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Backend)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotBackend.
func (in *SwiftSnapshotBackend) DeepCopy() *SwiftSnapshotBackend {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotGuestRef) DeepCopyInto(out *SwiftSnapshotGuestRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotGuestRef.
func (in *SwiftSnapshotGuestRef) DeepCopy() *SwiftSnapshotGuestRef {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotGuestRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotList) DeepCopyInto(out *SwiftSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotList.
func (in *SwiftSnapshotList) DeepCopy() *SwiftSnapshotList {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotSpec) DeepCopyInto(out *SwiftSnapshotSpec) {
	*out = *in
	out.GuestRef = in.GuestRef
	in.Backend.DeepCopyInto(&out.Backend)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotSpec.
func (in *SwiftSnapshotSpec) DeepCopy() *SwiftSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotStatus) DeepCopyInto(out *SwiftSnapshotStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CapturedAt != nil {
		in, out := &in.CapturedAt, &out.CapturedAt
		*out = (*in).DeepCopy()
	}
	if in.GuestSpec != nil {
		in, out := &in.GuestSpec, &out.GuestSpec
		*out = new(CapturedGuestSpec)
		**out = **in
	}
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]SnapshotDiskRef, len(*in))
		copy(*out, *in)
	}
	if in.MemorySnapshot != nil {
		in, out := &in.MemorySnapshot, &out.MemorySnapshot
		*out = new(MemorySnapshotRef)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3SnapshotStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotStatus.
func (in *SwiftSnapshotStatus) DeepCopy() *SwiftSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}
