//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSIVolumeSnapshotBackend) DeepCopyInto(out *CSIVolumeSnapshotBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSIVolumeSnapshotBackend.
func (in *CSIVolumeSnapshotBackend) DeepCopy() *CSIVolumeSnapshotBackend {
	if in == nil {
		return nil
	}
	out := new(CSIVolumeSnapshotBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapturedDataDisk) DeepCopyInto(out *CapturedDataDisk) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapturedDataDisk.
func (in *CapturedDataDisk) DeepCopy() *CapturedDataDisk {
	if in == nil {
		return nil
	}
	out := new(CapturedDataDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapturedGuestSpec) DeepCopyInto(out *CapturedGuestSpec) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(CapturedStorage)
		**out = **in
	}
	if in.InterfaceNames != nil {
		in, out := &in.InterfaceNames, &out.InterfaceNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DataDisks != nil {
		in, out := &in.DataDisks, &out.DataDisks
		*out = make([]CapturedDataDisk, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapturedGuestSpec.
func (in *CapturedGuestSpec) DeepCopy() *CapturedGuestSpec {
	if in == nil {
		return nil
	}
	out := new(CapturedGuestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapturedStorage) DeepCopyInto(out *CapturedStorage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapturedStorage.
func (in *CapturedStorage) DeepCopy() *CapturedStorage {
	if in == nil {
		return nil
	}
	out := new(CapturedStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityRegeneration) DeepCopyInto(out *IdentityRegeneration) {
	*out = *in
	if in.Regenerate != nil {
		in, out := &in.Regenerate, &out.Regenerate
		*out = make([]IdentityRegenerationItem, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityRegeneration.
func (in *IdentityRegeneration) DeepCopy() *IdentityRegeneration {
	if in == nil {
		return nil
	}
	out := new(IdentityRegeneration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalBackend) DeepCopyInto(out *LocalBackend) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalBackend.
func (in *LocalBackend) DeepCopy() *LocalBackend {
	if in == nil {
		return nil
	}
	out := new(LocalBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemorySnapshotRef) DeepCopyInto(out *MemorySnapshotRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemorySnapshotRef.
func (in *MemorySnapshotRef) DeepCopy() *MemorySnapshotRef {
	if in == nil {
		return nil
	}
	out := new(MemorySnapshotRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIBackend) DeepCopyInto(out *OCIBackend) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(SecretObjectReference)
		**out = **in
	}
	if in.SigningKeySecretRef != nil {
		in, out := &in.SigningKeySecretRef, &out.SigningKeySecretRef
		*out = new(SecretObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIBackend.
func (in *OCIBackend) DeepCopy() *OCIBackend {
	if in == nil {
		return nil
	}
	out := new(OCIBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIDataDiskArtifact) DeepCopyInto(out *OCIDataDiskArtifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIDataDiskArtifact.
func (in *OCIDataDiskArtifact) DeepCopy() *OCIDataDiskArtifact {
	if in == nil {
		return nil
	}
	out := new(OCIDataDiskArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCIDiskArtifact) DeepCopyInto(out *OCIDiskArtifact) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCIDiskArtifact.
func (in *OCIDiskArtifact) DeepCopy() *OCIDiskArtifact {
	if in == nil {
		return nil
	}
	out := new(OCIDiskArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCISnapshotStatus) DeepCopyInto(out *OCISnapshotStatus) {
	*out = *in
	if in.PushedAt != nil {
		in, out := &in.PushedAt, &out.PushedAt
		*out = (*in).DeepCopy()
	}
	if in.Disk != nil {
		in, out := &in.Disk, &out.Disk
		*out = new(OCIDiskArtifact)
		**out = **in
	}
	if in.DataDisks != nil {
		in, out := &in.DataDisks, &out.DataDisks
		*out = make([]OCIDataDiskArtifact, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCISnapshotStatus.
func (in *OCISnapshotStatus) DeepCopy() *OCISnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(OCISnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Backend) DeepCopyInto(out *S3Backend) {
	*out = *in
	if in.CredentialsSecretRef != nil {
		in, out := &in.CredentialsSecretRef, &out.CredentialsSecretRef
		*out = new(SecretObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Backend.
func (in *S3Backend) DeepCopy() *S3Backend {
	if in == nil {
		return nil
	}
	out := new(S3Backend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3SnapshotStatus) DeepCopyInto(out *S3SnapshotStatus) {
	*out = *in
	if in.UploadedAt != nil {
		in, out := &in.UploadedAt, &out.UploadedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3SnapshotStatus.
func (in *S3SnapshotStatus) DeepCopy() *S3SnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(S3SnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretObjectReference) DeepCopyInto(out *SecretObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretObjectReference.
func (in *SecretObjectReference) DeepCopy() *SecretObjectReference {
	if in == nil {
		return nil
	}
	out := new(SecretObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotDiskRef) DeepCopyInto(out *SnapshotDiskRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotDiskRef.
func (in *SnapshotDiskRef) DeepCopy() *SnapshotDiskRef {
	if in == nil {
		return nil
	}
	out := new(SnapshotDiskRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotScheduleRetention) DeepCopyInto(out *SnapshotScheduleRetention) {
	*out = *in
	if in.KeepLast != nil {
		in, out := &in.KeepLast, &out.KeepLast
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotScheduleRetention.
func (in *SnapshotScheduleRetention) DeepCopy() *SnapshotScheduleRetention {
	if in == nil {
		return nil
	}
	out := new(SnapshotScheduleRetention)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotTemplate) DeepCopyInto(out *SnapshotTemplate) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotTemplate.
func (in *SnapshotTemplate) DeepCopy() *SnapshotTemplate {
	if in == nil {
		return nil
	}
	out := new(SnapshotTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotTemplateMeta) DeepCopyInto(out *SnapshotTemplateMeta) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotTemplateMeta.
func (in *SnapshotTemplateMeta) DeepCopy() *SnapshotTemplateMeta {
	if in == nil {
		return nil
	}
	out := new(SnapshotTemplateMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestore) DeepCopyInto(out *SwiftRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestore.
func (in *SwiftRestore) DeepCopy() *SwiftRestore {
	if in == nil {
		return nil
	}
	out := new(SwiftRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestoreGuestRef) DeepCopyInto(out *SwiftRestoreGuestRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestoreGuestRef.
func (in *SwiftRestoreGuestRef) DeepCopy() *SwiftRestoreGuestRef {
	if in == nil {
		return nil
	}
	out := new(SwiftRestoreGuestRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestoreList) DeepCopyInto(out *SwiftRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestoreList.
func (in *SwiftRestoreList) DeepCopy() *SwiftRestoreList {
	if in == nil {
		return nil
	}
	out := new(SwiftRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestoreSnapshotRef) DeepCopyInto(out *SwiftRestoreSnapshotRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestoreSnapshotRef.
func (in *SwiftRestoreSnapshotRef) DeepCopy() *SwiftRestoreSnapshotRef {
	if in == nil {
		return nil
	}
	out := new(SwiftRestoreSnapshotRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestoreSpec) DeepCopyInto(out *SwiftRestoreSpec) {
	*out = *in
	out.SnapshotRef = in.SnapshotRef
	out.TargetGuest = in.TargetGuest
	if in.Identity != nil {
		in, out := &in.Identity, &out.Identity
		*out = new(IdentityRegeneration)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestoreSpec.
func (in *SwiftRestoreSpec) DeepCopy() *SwiftRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestoreStatus) DeepCopyInto(out *SwiftRestoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GuestRef != nil {
		in, out := &in.GuestRef, &out.GuestRef
		*out = new(SwiftRestoreGuestRef)
		**out = **in
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestoreStatus.
func (in *SwiftRestoreStatus) DeepCopy() *SwiftRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(SwiftRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftRestoreTarget) DeepCopyInto(out *SwiftRestoreTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftRestoreTarget.
func (in *SwiftRestoreTarget) DeepCopy() *SwiftRestoreTarget {
	if in == nil {
		return nil
	}
	out := new(SwiftRestoreTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshot) DeepCopyInto(out *SwiftSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshot.
func (in *SwiftSnapshot) DeepCopy() *SwiftSnapshot {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotBackend) DeepCopyInto(out *SwiftSnapshotBackend) {
	*out = *in
	if in.CSIVolumeSnapshot != nil {
		in, out := &in.CSIVolumeSnapshot, &out.CSIVolumeSnapshot
		*out = new(CSIVolumeSnapshotBackend)
		**out = **in
	}
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(LocalBackend)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3Backend)
		(*in).DeepCopyInto(*out)
	}
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(OCIBackend)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotBackend.
func (in *SwiftSnapshotBackend) DeepCopy() *SwiftSnapshotBackend {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotGuestRef) DeepCopyInto(out *SwiftSnapshotGuestRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotGuestRef.
func (in *SwiftSnapshotGuestRef) DeepCopy() *SwiftSnapshotGuestRef {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotGuestRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotList) DeepCopyInto(out *SwiftSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotList.
func (in *SwiftSnapshotList) DeepCopy() *SwiftSnapshotList {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotSchedule) DeepCopyInto(out *SwiftSnapshotSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotSchedule.
func (in *SwiftSnapshotSchedule) DeepCopy() *SwiftSnapshotSchedule {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSnapshotSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotScheduleList) DeepCopyInto(out *SwiftSnapshotScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftSnapshotSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotScheduleList.
func (in *SwiftSnapshotScheduleList) DeepCopy() *SwiftSnapshotScheduleList {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotScheduleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSnapshotScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotScheduleSpec) DeepCopyInto(out *SwiftSnapshotScheduleSpec) {
	*out = *in
	if in.StartingDeadlineSeconds != nil {
		in, out := &in.StartingDeadlineSeconds, &out.StartingDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.Retention != nil {
		in, out := &in.Retention, &out.Retention
		*out = new(SnapshotScheduleRetention)
		(*in).DeepCopyInto(*out)
	}
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotScheduleSpec.
func (in *SwiftSnapshotScheduleSpec) DeepCopy() *SwiftSnapshotScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotScheduleStatus) DeepCopyInto(out *SwiftSnapshotScheduleStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotScheduleStatus.
func (in *SwiftSnapshotScheduleStatus) DeepCopy() *SwiftSnapshotScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotSpec) DeepCopyInto(out *SwiftSnapshotSpec) {
	*out = *in
	out.GuestRef = in.GuestRef
	in.Backend.DeepCopyInto(&out.Backend)
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotSpec.
func (in *SwiftSnapshotSpec) DeepCopy() *SwiftSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSnapshotStatus) DeepCopyInto(out *SwiftSnapshotStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CapturedAt != nil {
		in, out := &in.CapturedAt, &out.CapturedAt
		*out = (*in).DeepCopy()
	}
	if in.GuestSpec != nil {
		in, out := &in.GuestSpec, &out.GuestSpec
		*out = new(CapturedGuestSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]SnapshotDiskRef, len(*in))
		copy(*out, *in)
	}
	if in.MemorySnapshot != nil {
		in, out := &in.MemorySnapshot, &out.MemorySnapshot
		*out = new(MemorySnapshotRef)
		**out = **in
	}
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3SnapshotStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(OCISnapshotStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSnapshotStatus.
func (in *SwiftSnapshotStatus) DeepCopy() *SwiftSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(SwiftSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}
