//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedDataField) DeepCopyInto(out *SeedDataField) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(SeedDataValueFrom)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedDataField.
func (in *SeedDataField) DeepCopy() *SeedDataField {
	if in == nil {
		return nil
	}
	out := new(SeedDataField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SeedDataValueFrom) DeepCopyInto(out *SeedDataValueFrom) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SeedDataValueFrom.
func (in *SeedDataValueFrom) DeepCopy() *SeedDataValueFrom {
	if in == nil {
		return nil
	}
	out := new(SeedDataValueFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSeedProfile) DeepCopyInto(out *SwiftSeedProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSeedProfile.
func (in *SwiftSeedProfile) DeepCopy() *SwiftSeedProfile {
	if in == nil {
		return nil
	}
	out := new(SwiftSeedProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSeedProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSeedProfileList) DeepCopyInto(out *SwiftSeedProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SwiftSeedProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSeedProfileList.
func (in *SwiftSeedProfileList) DeepCopy() *SwiftSeedProfileList {
	if in == nil {
		return nil
	}
	out := new(SwiftSeedProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SwiftSeedProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SwiftSeedProfileSpec) DeepCopyInto(out *SwiftSeedProfileSpec) {
	*out = *in
	if in.UserDataFrom != nil {
		in, out := &in.UserDataFrom, &out.UserDataFrom
		*out = new(SeedDataValueFrom)
		(*in).DeepCopyInto(*out)
	}
	if in.MetaDataFrom != nil {
		in, out := &in.MetaDataFrom, &out.MetaDataFrom
		*out = new(SeedDataValueFrom)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkDataFrom != nil {
		in, out := &in.NetworkDataFrom, &out.NetworkDataFrom
		*out = new(SeedDataValueFrom)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SwiftSeedProfileSpec.
func (in *SwiftSeedProfileSpec) DeepCopy() *SwiftSeedProfileSpec {
	if in == nil {
		return nil
	}
	out := new(SwiftSeedProfileSpec)
	in.DeepCopyInto(out)
	return out
}
